# fly.toml app configuration file generated for rotate-calvary on 2023-05-15T23:43:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rotate-calvary"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
